### ISSUE TITLE
Modal: dynamically change `aria-hidden` based on modal state

### ISSUE THREAD

**Issue by tinymachine** [markteekman/accessible-astro-components#17]
Closed modals don't have `aria-hidden` set to false, so screen readers (like VoiceOver on macOS and iOS) will still read the contents of closed modals. This should probably be defaulted to true, and changed to false in the `openModal()` method, and reset to true in `closeModal()`.

**Comment by markteekman** [comment]
Good find @tinymachine, thank you! I'll add it to the list 🙂

**Comment by tinymachine** [comment]
My pleasure, @markteekman!

**Comment by markteekman** [comment]
@tinymachine tested it myself and read into it a little more but it should work fine as it is! The modal has it's `visibility` at `hidden` and that should be enough: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden.

**Comment by tinymachine** [comment]
Thanks for explaining, @markteekman! That behavior makes perfect sense, and works correctly for me on your [Modal demo page](https://components.accessible-astro.dev/modal/). Weirdly, I'm experiencing an issue where embedded Vimeo videos in modals are being read by VoiceOver on iOS 15.4.1 even when the modals are closed (i.e. `visibility: hidden`), but adding `aria-hidden="true"` to the modal element fixes it. Not sure if a bug in my code or maybe in Safari/VoiceOver? I'll troubleshoot and let you know if I sort it out. Thanks again!

**Comment by markteekman** [comment]
@tinymachine it got me thinking, could it have anything to do with the embded Vimeo video being an `iframe`? And thus it being handled differently as a child of a parent with `visibility: hidden`?
