### ISSUE TITLE
`Preprocessor dependency "sass" not found. Did you install it?` error

### ISSUE THREAD

**Issue by tinymachine** [markteekman/accessible-astro-components#19]
Some components rely on sass (e.g. `Modal.astro` uses the `lang="scss"` attribute on the `<style>` tag), but sass isn't included in the `package.json`. Probably should be added as a dev dependency?

**Comment by markteekman** [comment]
Good one @tinymachine, that should indeed be added as a dev dependency! Thanks again for going through these components so thoroughly, it really helps improve the quality of the project 🙂 I'll add it in the next update!

**Comment by tinymachine** [comment]
My pleasure, @markteekman -- thank you for sharing these components with the world!

**Comment by ChrisChinchilla** [comment]
@markteekman I am not sure if I am missing something, but following the install steps and adding a pagination component, I still see this error. Is there a docs step missing?

**Comment by markteekman** [comment]
Hey @ChrisChinchilla, hmm, that's weird. Does this also happen with the other components or only with the pagination?

**Comment by ChrisChinchilla** [comment]
@markteekman Not needed any of the others, but tried skip links quickly, same error

**Comment by markteekman** [comment]
@ChrisChinchilla just tested this with a fresh Astro install and can indeed confirm the issue. It seems Sass is needed inside the project as wel (having it as a dependency inside the components package isn't enough), so doing a `npm install sass` in your project solves it.

However, I do find this to be an unnecessary extra step for those who won't be using Sass in their project 🤔 So what I think I'll do is just write the components in CSS, seeing as I'm only using Sass's nesting feature and nothing more. I'll work on it when I have some time! Thanks for noticing 🙂

**Comment by markteekman** [comment]
@ChrisChinchilla this issue should now be resolved in the latest release 🙂
