### ISSUE TITLE
README.md # id links don't work on github.com

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [markteekman/accessible-astro-components#50]
Looking at the _Skip to:_ links in the README.md:

* Actual link: `https://github.com/markteekman/accessible-astro-components#Accordion`
* Expected link: `https://github.com/markteekman/accessible-astro-components#accordion`

Note the casing difference.

**Comment by markteekman** [comment]
Hey @JoshuaKGoldberg, oh I didn't know! It always worked on the [NPM page](https://www.npmjs.com/package/accessible-astro-components), it seems to be more forgiving of capitals then GitHub 🙂 Thanks for noticing!

**Comment by JoshuaKGoldberg** [comment]
Fixed by edb6f19 :) thanks!
