### ISSUE TITLE
Add new Forms & Inputs component

### ISSUE THREAD

**Issue by markteekman** [markteekman/accessible-astro-components#65]
Forms can be very complex, not just accessibility wise. We can make a small start by adding some default components / wrappers with some accessibility standards baked in.

### Notes
- TypeScript support
- Vanilla example: https://codepen.io/markteekman/pen/Yzdovxo

**Comment by puria** [comment]
😍 Specially buttons with good wcag and aria roles would be very appreciated!

**Comment by markteekman** [comment]
Thanks @puria! What precisely did you have in mind when it comes to (form) buttons and aria roles? When talking semantics, there shouldn't be need for them in this specific use case. Using a button with `type="submit"` would be sufficient 🙂

**Comment by markteekman** [comment]
Close this issue in favor of adding it in the Accessible Astro Starter by default: https://github.com/markteekman/accessible-astro-starter/issues/83.
