### ISSUE TITLE
Accordions could work without JS

### ISSUE THREAD

**Issue by garyb1** [markteekman/accessible-astro-components#70]
When I turn off JavaScript in Chrome the accordion component stays in a stacked accordion and cannot expand/collapse.

Maybe we should have a Minimum Viable experience and enhance that experience with JS is enabled. 
We could expose the accordion heading and content and when JS is enabled enforce the accordion pattern?

Just a thought 🙂

**Comment by garyb1** [comment]
I just realised I should have put this on the discussion board. Apologies.

**Comment by markteekman** [comment]
No problem @garyb1 😊
