### ISSUE TITLE
aXe/Lighthouse failure on SkipLinks: "Skip links are not focusable."

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [markteekman/accessible-astro-components#82]
👋 this is a fantastic library, thanks for making it! I'm using `SkipLinks` now on 2024.squiggleconf.com and seeing in aXe accessibility reports:

```plaintext
🔺 Skip links are not focusable.

Failing Elements
--
Skip to main content
<a href="#main-content">
```

Looking at the skip link's HTML:

```html
<div class="skip-links">
  <a href="#main-content">Skip to main content</a>
</div>
```

I can definitely keyboard focus / <kbd>tab</kbd>-switch to the skip link. So either this is an edge case I don't understand (very possible) or a false positive from aXe. But either way, is this something that can be fixed to not have an aXe complaint on pages?

**Comment by markteekman** [comment]
Hey @JoshuaKGoldberg, thank you for your kind words 😊 Hmmm, that's a weird one! I'll have to look into it a little bit 🤔

**Comment by markteekman** [comment]
Hey @JoshuaKGoldberg, I actually get two accessibility issues (best practices) on your website:

<img width="416" alt="Scherm­afbeelding 2024-09-03 om 16 59 24" src="https://github.com/user-attachments/assets/93728e20-9690-4ea5-906b-bdf1cb2ba78e">

Looking at your HTML structure, it makes sense, the skip links are missing a focusable target. You can solve this by adding `id="main-content"` to the `<main>` element. Ideally you'd want to move the `<header>` to the same level as your `<main>` and your `<footer>` and with that, both warnings should be gone 😄 

Change this:
<img width="803" alt="Scherm­afbeelding 2024-09-03 om 16 56 55" src="https://github.com/user-attachments/assets/084160d7-9518-469d-b5ed-2c5199c69482">


To this:
<img width="803" alt="Scherm­afbeelding 2024-09-03 om 16 57 52" src="https://github.com/user-attachments/assets/218b45db-37a5-4cef-9b8f-6c97315123bc">

Let me know how that works out!

**Comment by JoshuaKGoldberg** [comment]
Aha! Thank you, that fixed it.

I can kind of get how that error came to be. `<a href="#main-content">` wasn't focusable because `#main-content` didn't exist.
